[package]
name = "mer_frontend_derive"
version = "0.1.0"
authors = ["Paul Volavsek <paul.volavsek@gmail.com>"]
edition = "2018"

[features]

default = ["std"]

std = [
  "snafu/std",
  "log/std"
]

[dependencies]
mer = { path = "../../../mer" }
mer_frontend_derive_macros = { path = "../macros" }


snafu = { version = "0.6.9", default-features = false }
log = { version = "0.4", default-features = false }

[dev-dependencies]
mer_backend_in_process = { path = "../../../backends/in-process" }

serde = "1.0"
rand = "0.8"
flexi_logger = "0.16"
tokio = { version = "1.0", features = ["sync"] }

[[test]]
name = "test"
path = "test/tests.rs"
