[workspace]
members = [
  "mer",
  "frontends/derive/core",
  "frontends/derive/macros",
  "frontends/register",
  "frontends/logger",
  "middlewares/router",
  "middlewares/authentication",
  "backends/http",
  "backends/serialport",
  "backends/in-process"
]
