[package]
name = "mer"
version = "0.1.0"
authors = ["Paul Volavsek <paul.volavsek@gmail.com>"]
edition = "2018"

[features]

default = ["std", "threadsafe"]

std = ["serde/std", "snafu/std"]
threadsafe = ["spin"]

[dependencies]
serde = { version = "1.0.116", default-features = false, features = ["alloc"] }

spin = { version = "0.7.0", optional = true }

snafu = { version = "0.6.9", default-features = false }
log = { version = "0.4", default-features = false }

[dev-dependencies]
rand = "0.8"
flexi_logger = "0.17"
