[package]
name = "mer"
version = "0.1.0"
authors = ["Paul Volavsek <paul.volavsek@gmail.com>"]
edition = "2018"

[features]

default = ["std"]

std = ["serde/std", "anyhow/std"]

c_ffi = ["derive_macros"]
cpp_ffi = ["derive_macros"]

[dependencies]
derive_macros = { path = "../derive_macros", optional = true }

serde = { version = "1.0.116", default-features = false, features = ["alloc"] }

spin = "0.7.0"

anyhow = { version = "1.0", default-features = false }
log = { version = "0.4", default-features = false }

[dev-dependencies]
serde_json = "1.0.57"
rand = "0.8"
flexi_logger = "0.17"

[build-dependencies]
cbindgen = "0.16"
