[package]
name = "mer"
version = "0.1.0"
authors = ["Paul Volavsek <paul.volavsek@gmail.com>"]
edition = "2018"

[features]

default = ["std"]

std = ["serde/std", "anyhow/std"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc"] }

anyhow = { version = "1.0", default-features = false }
log = { version = "0.4", default-features = false }

async-trait = "0.1"

tokio = { version = "1.0", feature="sync"}
[dev-dependencies]
serde_json = "1.0.57"
rand = "0.8"
flexi_logger = "0.17"
tokio-test = "0.4"
