[package]
name = "mer"
version = "0.1.0"
authors = ["Paul Volavsek <paul.volavsek@gmail.com>"]
edition = "2018"

[features]

default = ["std"]

std = ["serde/std", "anyhow/std", "thiserror"]

[dependencies]
serde = { version = "1.0.116", default-features = false, features = ["alloc"] }


anyhow = { version = "1.0", default-features = false }
thiserror = { version = "1.0", optional = true }
log = { version = "0.4", default-features = false }

spin = "0.7.0"

[dev-dependencies]
serde_json = "1.0.57"
rand = "0.8"
