[package]
name = "mer_frontend_register"
version = "0.1.0"
authors = ["Paul Volavsek <paul.volavsek@gmail.com>"]
edition = "2018"

[features]

[dependencies]
mer = { path = "../../mer" }

serde = "1.0.116"

snafu = { version = "0.6.9", default-features = false }
log = { version = "0.4", default-features = false }

[dev-dependencies]
mer_backend_in_process = { path = "../../backends/in-process" }

rand = "0.8"
flexi_logger = "0.16"

[[test]]
name = "test"
path = "test/tests.rs"
